### ISSUE TITLE
Replace bottom-corner logo with bigger, top logo in Word and PDF templates

### ISSUE THREAD

**Issue by ClaytonJY** [MethodsConsultants/mcdocs#11]
This might be difficult, but I think it would make for a slightly nicer report default. The ioslides template works analogously to this already.

**Comment by scheidec** [comment]
Where do you envision this going: top left, top center, or top right?  I thought about this too but wasn't sure where to put it if we wanted to include a title, author and date at the top of the first page of the report as well.

**Comment by ClaytonJY** [comment]
I was thinking top-center, a lot bigger than the corner logos, and above the title/author/etc, but I'm open to anything that looks good.

It might be one thing to add the new logo, and another thing entirely to remove the bottom-corner logo on the first page, but 2 logos on the first page would be weird/bad.
